### ISSUE TITLE
Cannot run unit tests

### ISSUE THREAD

**Issue by chewy94** [championswimmer/vuex-persist#41] opened 2018-03-22 17:46 UTC
I am attempting to use `vue-test-utils` and `jest` to run some unit tests on my vuex actions. I am running into the error below. Any ideas on how I can get this resolved?

```
 FAIL  test/unit/specs/masternode/Provision.spec.js
  ● Test suite failed to run

    TypeError: Cannot read property '_config' of undefined

    
      
      at new VuexPersistence (node_modules/vuex-persist/dist/index.js:133:44)
      at Object.<anonymous> (src/store/index.js:60:17)
      at Object.<anonymous> (src/contracts/MNProposedMarket.js:19:14)
      at Object.<anonymous> (src/store/modules/app/actions.js:35:25)
      at Object.<anonymous> (src/store/modules/app/index.js:7:16)
      at Object.<anonymous> (src/store/modules/index.js:7:12)
      at Object.<anonymous> (test/unit/specs/masternode/Provision.spec.js:27:16)
```

Here is my spec so far:
```javascript
describe('AppActions', () => {
  const vuexLocal = new VuexPersist({
    storage: window.localStorage,
    modules: ['app', 'masternode', 'marketplace'],
  })
  let store

  beforeEach(() => {
    store = new VuexStore ({
      plugins: [vuexLocal.plugin]
    })
  })
})
```

**Comment by sbancal** [comment] 2018-03-23 15:34
Same problem here while trying to test with `jest` + `vue-test-utils`

```
 FAIL  test/unit/specs/ProjectSwitch.spec.js
  ● Test suite failed to run

    TypeError: Cannot read property '_config' of undefined

       7 | Vue.use(Vuex)
       8 | 
    >  9 | const vuexLocal = new VuexPersistence({
      10 |   key: 'itlogs',
      11 |   storage: window.sessionStorage,
      12 |   reducer: state => ({ currentView: state.currentView }),
      
      at new VuexPersistence (node_modules/vuex-persist/dist/index.js:137:44)
      at Object.<anonymous> (src/store/index.js:9:66)
      at Object.<anonymous> (test/unit/specs/ProjectSwitch.spec.js:7:14)
```

Here is my `src/store/index.js` :

```javascript
import Vue from 'vue'
import Vuex from 'vuex'
import VuexPersistence from 'vuex-persist'
import { mutations } from './mutations'
import * as actions from './actions'

Vue.use(Vuex)

const vuexLocal = new VuexPersistence({
  key: 'itlogs',
  storage: window.sessionStorage,
  reducer: state => ({ currentView: state.currentView }),
  filter: mutation => (mutation.type === 'SWITCHTHEVIEW')
})

export const state = {
  csrfmiddlewaretoken: undefined,
  userName: undefined,
  projects: [],
  currentProjectId: undefined,
  currentProject: undefined,
  currentView: undefined
}

export default new Vuex.Store({
  state,
  mutations,
  actions,
  plugins: [vuexLocal.plugin]
})
```

and `test/unit/specs/ViewSwitch.spec.js` :

```javascript
import { shallow, createLocalVue } from '@vue/test-utils'
import Vuex from 'vuex'
import VuexPersistence from 'vuex-persist'

import ViewSwitch from '@/components/ViewSwitch'
import * as actions from '@/store/actions'
import { mutations } from '@/store/mutations'
import { state } from '@/store/index'

const localVue = createLocalVue()

const vuexLocal = new VuexPersistence({
  key: 'itlogs',
  storage: window.sessionStorage,
  reducer: state => ({ currentView: state.currentView }),
  filter: mutation => (mutation.type === 'SWITCHTHEVIEW')
})


localVue.use(Vuex)

describe('ViewSwitch.vue', () => {
  let store

  beforeEach(() => {
    store = new Vuex.Store({
      state,
      actions,
      mutations,
      plugins: [vuexLocal.plugin]
    })
  })

  const setup = (viewName) => {
    mutations.SWITCHTHEVIEW(
      store.state, { viewName }
    )
  }

  it('should suggest browse and settings', () => {
    setup('browse')
    const wrapper = shallow(ViewSwitch, {store, localVue})
    const allDropdownItems = wrapper.findAll('.dropdown-item')
    expect(allDropdownItems.length).toBe(2)
    expect(allDropdownItems.at(0).text()).toBe('browse')
    expect(allDropdownItems.at(1).text()).toBe('settings')
  })
})

```

**Comment by sbancal** [comment] 2018-03-23 15:50
Seems related to this line : https://github.com/championswimmer/vuex-persist/blob/0a9ff26f2ead820341c79a40a3c1b02f3e92e971/src/index.ts#L97

**Comment by sbancal** [comment] 2018-03-26 13:09
Does that mean vuex-persist is not intended to be used within a project that has unit testing with jest and vue-test-utils?

**Comment by championswimmer** [comment] 2018-03-28 22:04
should be fixed in `v1.1.6`

**Comment by sbancal** [comment] 2018-03-29 10:44
Thanks @championswimmer , I've tried v1.1.6 ... original error disappeared, but a new one came up : 

```
 FAIL  test/unit/specs/ProjectSwitch.spec.js
  ● Test suite failed to run

    TypeError: Cannot read property 'getItem' of undefined

      23 | }
      24 | 
    > 25 | export default new Vuex.Store({
      26 |   state,
      27 |   mutations,
      28 |   actions,
      
      at VuexPersistence.restoreState (node_modules/vuex-persist/dist/index.js:201:43)
      at VuexPersistence.plugin (node_modules/vuex-persist/dist/index.js:225:40)
      at node_modules/vuex/dist/vuex.common.js:353:46
          at Array.forEach (<anonymous>)
      at new Store (node_modules/vuex/dist/vuex.common.js:353:11)
      at Object.<anonymous> (src/store/index.js:25:1)
      at Object.<anonymous> (test/unit/specs/ProjectSwitch.spec.js:7:14)
```

**Comment by wesleycole** [comment] 2018-04-15 15:06
Same problem as @sbancal for me. Fresh install of vuex-persist and Jest and I get cannot read propery 'getItem' whenever running tests.

**Comment by SkyzohKey** [comment] 2018-04-23 12:04
Same issue here, we are using vuex-persist to store some credentials on the sessionStorage for a company internal tool but it seems that it is currently not possible to run tests. Same error as above.

**Comment by championswimmer** [comment] 2018-04-23 12:43
Sorry I had been really swamped by work. I'll fix this, this week.

**Comment by championswimmer** [comment] 2018-05-03 06:17
can someone link me to a repository where I can reproduce this.

**Comment by championswimmer** [comment] 2018-05-03 06:19
For unit testing purpose you'll have to use https://github.com/championswimmer/vuex-persist/blob/master/src/MockStorage.ts probably. it is meant for browser-less testing.

**Comment by championswimmer** [comment] 2018-05-03 06:31
I'll reopen if https://github.com/championswimmer/vuex-persist/blob/master/README.md#jest this doesn't fix it

**Closed by championswimmer** 2018-05-03 06:31 UTC

**Comment by sbancal** [comment] 2018-05-03 10:11
Thanks. Seems to fix on my side ... (another problem comes up, but I guess it's related to `jest-localstorage-mock` package).

**Comment by mpconte** [comment] 2019-02-20 17:47
@championswimmer What exactly do you mean by using **MockStorage.ts** to run the `vue-test-utils`? 

I'm not using jest, but I still encounter the same error as @sbancal that seems to occurs here:

`TypeError:` Cannot read property 'getItem' of undefined
    at VuexPersistence.restoreState (~/vuex-persist/dist/esm/index.js:189:1)`

I'm using **vuex-persist 2.0.0**

**Comment by championswimmer** [comment] 2019-02-20 22:08
Use MockStorage instead of window.localStorage in the `storage` option of this plugin when testing.

**Comment by mpconte** [comment] 2019-02-21 14:17
@championswimmer I see, thanks!
