### ISSUE TITLE
When is the plugin ready to be used?

### ISSUE THREAD

**Issue by PierBover** [championswimmer/vuex-persist#15] opened 2017-11-30 14:49 UTC
Loading from `localStorage` seems immediate when the application starts, but when writing to the vuex store persistence doesn't seem to work until some time has passed.

If I do this in root component the state in `localStorage` doesn't change:

```
const root = new Vue({
	el: '#app',
	router,
	store,
	render: (h) => h(App),
	mounted () {
		store.commit('persistent/SET_TEST_VAR', true);
		console.log(store.state.persistent.test_var);
	}
});
```

If I do this instead it works fine:

```
setTimeout(() => {
	store.commit('persistent/SET_TEST_VAR', true);
	console.log(store.state.persistent.test_var);
}, 1000);
```

**Comment by kylewelsby** [comment] 2017-11-30 20:16
I managed to find a workaround if you're using [VueRouter](https://router.vuejs.org/en/)

Given you have the strict `RESTORE_MUTATION` setup;
```javascript
// ./store/index.js
import VuexPersistPatch from './plugins/vuex-persist-patch'

export default new Vuex.Store({
  mutations: Object.assign(mutations, {
    RESTORE_MUTATION: vuexLocal.RESTORE_MUTATION
  }),
  plugins: [
    vuesLocal.plugin,
    VuexPersistPatch()
  ]
})
```


```javascript
// ./plugins/vuex-persist-patch.js
export default function vuexPersistPatch () {
  return store => {
    store.subscribe(mutation => {
      if (mutation.type === 'RESTORE_MUTATION') {
        store._vm.$root.$emit('storageReady')
      }
    })
  }
}
```


Take special note to using `store._vm` to receive the event from the bus.
```javascript
// ./router/index.js
import store from '../store'

router.beforeEach((to, from, next) => {
  // Hold the request, until the Storage is complete.
  store._vm.$root.$on('storageReady', () => {
    next()
  })
})
```

**Comment by PierBover** [comment] 2017-11-30 20:45
Thanks @kylewelsby for the suggestion.

Seems overly complicated though since `localStorage` interactions are not async.

**Comment by PierBover** [comment] 2017-11-30 21:07
I ended using [vuex-persistedstate](https://github.com/robinvdvleuten/vuex-persistedstate) which works as expected.

**Comment by kylewelsby** [comment] 2017-12-01 09:10
I think it's designed like this to support WebSQL and IndexedDB which are
Asynchronous.   So, minor trade off for confirmed data.

I think a graceful solution of holding the app for load, or work with
SW.js.

-\0_0/-

**Comment by championswimmer** [comment] 2017-12-07 10:51
The problem has been resolved in v1.0

If the store is **not** async (you're using localStorage), then vuex-persist will synchrnously  restore state and you won't feel like "The store is not immediately restored"

**Closed by championswimmer** 2017-12-07 10:51 UTC

**Comment by svenewers** [comment] 2017-12-12 05:34
@championswimmer I've just tested out the changes in version 1.0 and it seems as though your fix for this behavior does not apply when using sessionStorage() instead of localStorage().  
Would it be possible to make the two types of storage behave the same, sync way, or is there something that would prevent someone from doing that? It'd really helpe if sessionStorage() could also work this way.  
Thanks for your work on this project :)

**Comment by CosX** [comment] 2017-12-13 10:00
Thank you @PierBover. I managed to do this with localforage inspired by your plugin.

```
//first define a plugin that emits when the state has been persisted
const vuexPersistEmitter = () => {
    return store => {
        store.subscribe(mutation => {
            if (mutation.type === 'RESTORE_MUTATION') {
                store._vm.$root.$emit('storageReady');
            }
        });
    }
};

//I only needed to define strict mode here and not in the store.
const vuexLocal = new VuexPersistence({
    strictMode: true,
    asyncStorage: true,
    storage: localforage
});

export default new Vuex.Store({
   ...,
    mutations: {
        RESTORE_MUTATION: vuexLocal.RESTORE_MUTATION
    },
    plugins: [
        vuexLocal.plugin,
        vuexPersistEmitter()
      ]
});
```
And then in any kind of component:

```
const app = new Vue({
    store,
    ...App,
    mounted() {
        const self = this;
        self.$store._vm.$root.$on('storageReady', () => {
            self.$store.dispatch('somethingThatDependsOnTheStateBeingFilled');
        });
    }
});
```

**Comment by benitogf** [comment] 2018-01-16 13:41
Hi, thanks for this plugin 👍 using custom methods for the storage (setItem, getItem, etc) instead of localforage will fail unless the flag [here](https://github.com/championswimmer/vuex-persist/blob/master/src/index.ts#L90) is set too

**Comment by karneaud** [comment] 2018-03-21 00:00
Tried this plugin with 1.0.0 and "The store is not immediately restored". Is there a fix of this in any of the new versions or do I implement a workaround?

**Comment by karneaud** [comment] 2018-03-29 21:28
Tries this plugin with 1.1.5 and still the same issue. using @CosX  workaround does help but only if the state is restored....so I have to check the regular way and via store events

```
created(){
      this.setFetching({fetching: true})
      this.$store._vm.$root.$on('storageReady', () => {
        this.setGameStates()
        this.setFetching({fetching: false})
      });
    },
    mounted() {
      this.setGameStates()
    }
```

**Comment by rulrok** [comment] 2018-09-24 18:31
Just a note if you are having this timing issue on production mode and is trying to use the subscribe trick.
As you will have `strict` set to false, the `subscribe` with `RESTORE_MUTATION` won't work.
That's because the store won't commit, but rather replace the state.

Look the code here:
https://github.com/championswimmer/vuex-persist/blob/a5033b529f66a4fe6ee0e44f8d2e656a826654e6/src/index.ts#L163-L167

**Comment by bvelastegui** [comment] 2019-03-08 16:00
> 
> 
> I managed to find a workaround if you're using [VueRouter](https://router.vuejs.org/en/)
> 
> Given you have the strict `RESTORE_MUTATION` setup;
> 
> ```js
> // ./store/index.js
> import VuexPersistPatch from './plugins/vuex-persist-patch'
> 
> export default new Vuex.Store({
>   mutations: Object.assign(mutations, {
>     RESTORE_MUTATION: vuexLocal.RESTORE_MUTATION
>   }),
>   plugins: [
>     vuesLocal.plugin,
>     VuexPersistPatch()
>   ]
> })
> ```
> 
> ```js
> // ./plugins/vuex-persist-patch.js
> export default function vuexPersistPatch () {
>   return store => {
>     store._vm.$root.$data['vue-persist-patch-delay'] = true
> 
>     store.subscribe(mutation => {
>       if (mutation.type === 'RESTORE_MUTATION') {
>         store._vm.$root.$data['vue-persist-patch-delay'] = false
> 
>         store._vm.$root.$emit('storageReady')
>       }
>     })
>   }
> }
> ```
> 
> Take special note to using `store._vm` to receive the event from the bus.
> 
> ```js
> // ./router/index.js
> import store from '../store'
> 
> router.beforeEach((to, from, next) => {
>   if (store._vm.$root.$data['vue-persist-patch-delay']) {
> 
>     // Hold the request, until the Storage is complete.
>     store._vm.$root.$on('storageReady', () => {
>       next({path: to.path, query: to.query, params: to.params})
>     })
>   } else {
>     // YOUR OTHER RULES GO HERE
>   }
> })
> ```

@kylewelsby Thank you !! this served me!

**Comment by morphatic** [comment] 2019-04-07 22:46
PR #107 is intended to address the issue raised by @rulrok. I've tested locally and found that I'm able to consistently get `vuex-persist` to restore the state **before** any other mutations are committed.
