### ISSUE TITLE
when i use reducer, there is some bug

### ISSUE THREAD

**Issue by chavesgu** [championswimmer/vuex-persist#85] opened 2018-12-10 13:14 UTC
i want use reducer to save some data that i want to save,but when i refresh Browser, the data is lost,why

**Comment by kyriediculous** [comment] 2019-02-12 16:10
Same here.

I use the reducer to save part of my state, this gets saved but upon refresh turns into undefined.

**Comment by championswimmer** [comment] 2019-02-12 17:35
A repository with an example so I can reproduce?

**Comment by kyriediculous** [comment] 2019-02-14 10:48
Not really, my project is quite large. 

Seems to be only happening with sessionStorage, even though that should last for the browser session. 

I use this to save Ethereum wallets, they are objects with prototypes. (https://docs.ethers.io/ethers.js/html/api-wallet.html#encrypted-json-wallets) 

If I have time I'll make something to reproduce but if you're faster please try using sessionStorage + reducer and see if it persists for the lifetime of the browser session on refresh. 

```
const vuexSession = new VuexPersist({
  key: 'keypair',
  storage: window.sessionStorage,
  reducer: state => state.user.wallet,
  restoreState: (key, storage) => {
    let item = storage.getItem(key)
    if (item && item !== 'undefined') {
      item = JSON.parse(item)
      return Wallet.fromMnemonic(item.signingKey.mnemonic)
    } else {
      return 
    }
  },
  saveState: (key, state, storage) => storage.setItem(key, JSON.stringify(state)),
})
```

**Comment by kyriediculous** [comment] 2019-02-14 16:36
Now it is also happening with localStorage. 

The cause is that the state is not being properly rehydrated when using the reducer @championswimmer 

In restoreState the object is being retrieved and parsed, the prototype is being attached back to it. This is then returned from restoreState but when I call my upon my state after that the property is undefined. 

I just confirmed I do not have this issue when using filter

**Comment by championswimmer** [comment] 2019-02-15 06:54
It is mentioned on the README 
https://github.com/championswimmer/vuex-persist#note-on-localforage-and-async-stores

**Comment by kyriediculous** [comment] 2019-02-15 10:25
I'm starting to doubt you have basic english reading capabilities.

**Comment by championswimmer** [comment] 2019-02-15 17:29
<img width="930" alt="image" src="https://user-images.githubusercontent.com/1327050/52873572-57791b00-3175-11e9-89d8-382b88422792.png">

**Comment by championswimmer** [comment] 2019-02-15 17:31
People forgetting that localStorage stores strings, while IndexedDB can store objects is very fundamental to frontend development, and if someone has crossed the chasms of frontend frameworks, webpack bundles, vue, vuex, flux patterns, typescript and ended up on this library, I believe it is certainly out of scope to teach that all over again here.

**Closed by championswimmer** 2019-02-15 17:31 UTC
